version: '3.9'

services:
  postgres:
    image: ankane/pgvector
    container_name: postgres_pgvector
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: highlights_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
